### ISSUE TITLE
Adding paragraphs to comments

### ISSUE THREAD

**Issue by paul-carron** [PacktPublishing/Full-Stack-React-Projects#3]
I'm reading Full Stack React Projects alongside working through the sample code, which I'm trying to edint and add to in order to get an understanding of it.

One thing I've done is to take this code:
`https://github.com/PacktPublishing/Full-Stack-React-Projects/tree/master/Chapter05/mern-social`

and in file client/post/Post.js I've tried to add paragraphs to the comments. I did this by changing:

```
<Typography component="p" className={classes.text}>
        {this.props.post.text}
</Typography>
```

to:

```
<Typography component="p" className={classes.text} paragraph="true">
        {this.props.post.text}
</Typography>
```

that didn't work so I tried:

```
<Typography component="p" className={classes.text} paragraph={true}>
        {this.props.post.text}
</Typography>
```

which also didn't work.

I'v since spent some time looking at this and think one of the above should work. Is it possible that this is getting overridden by something else in the code? I've checked through it and can't see anything but am not familiar enough with the code to be sure.

Cheers
Paul

**Comment by shamahoque** [comment]
Hi Paul,

Do you want to add paragraphs to the Post text or a comment in the Comments section? A couple of points: 

- The code you are editing is actually the text of the post and not comments (code for the comments section text is in client/post/Comments.js).

- The paragraph={true} attribute in Typography just [adds a bottom-margin to the whole text](https://material-ui.com/api/typography/) (not sure if this is the behavior you are expecting). With this attribute set to true in this code, nothing changes in the appearance of the Post text because it already has a margin value set in the {classes.text}.

Hope this helps.

**Comment by paul-carron** [comment]
Thanks for the quick reply and apologies nor not being clear. It is indeed the Post to which I wish to be to add paragraphs.

What you say makes sense. As I understand, I would need an additional `Typography` for a second paragraph and another for a third etc. does that seem correct?

**Comment by paul-carron** [comment]
FYI I've come up with this:

```
      <pre>
        <Typography component="p" className={classes.text}>
          {this.props.post.text}
        </Typography>
      </pre>
```

The `<pre>` tag preservers the whitespace and line breaks inside the tags as is.

If there is a better way to do this I'd be keen to hear it.

**Comment by shamahoque** [comment]
Using the `<pre>` tag is a nifty solution to achieve this, and I think definitely better than having to use multiple Typography components. 

Thank you for sharing your solution.
